package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

var docgenCmd = &cobra.Command{
	Use:    "docgen",
	Short:  "Generate Markdown docs for every CLI command (hidden; used by docs-site build)",
	Hidden: true,
	RunE: func(cmd *cobra.Command, args []string) error {
		out, _ := cmd.Flags().GetString("out")
		if out == "" {
			return fmt.Errorf("--out is required")
		}
		if err := os.MkdirAll(out, 0o755); err != nil {
			return fmt.Errorf("create output dir: %w", err)
		}

		// Drop the auto-generated "Auto generated by spf13/cobra on DATE" footer.
		// The date stamp causes every regen to produce a diff (every day), which
		// breaks the cli-reference-stale-check.yml CI guard for committed CLI
		// reference. Mkdocs theme already surfaces last-edited timestamps via
		// page metadata.
		RootCmd.DisableAutoGenTag = true

		linkHandler := func(name string) string { return name }
		filePrepender := func(filename string) string {
			base := strings.TrimSuffix(filepath.Base(filename), ".md")
			title := strings.ReplaceAll(base, "_", " ")
			return fmt.Sprintf("---\ntitle: %s\n---\n\n", title)
		}

		return doc.GenMarkdownTreeCustom(RootCmd, out, filePrepender, linkHandler)
	},
}

func init() {
	docgenCmd.Flags().String("out", "", "Output directory for generated Markdown (required)")
	RootCmd.AddCommand(docgenCmd)
}
