package cli

import (
	"fmt"
	"os"
	"time"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

var mangenCmd = &cobra.Command{
	Use:    "mangen",
	Short:  "Generate man pages for every CLI command (hidden; used by 'make man')",
	Hidden: true,
	RunE: func(cmd *cobra.Command, args []string) error {
		out, _ := cmd.Flags().GetString("out")
		if out == "" {
			return fmt.Errorf("--out is required")
		}
		if err := os.MkdirAll(out, 0o755); err != nil {
			return fmt.Errorf("create output dir: %w", err)
		}

		// Suppress the "Auto generated by spf13/cobra on DATE" footer.
		// Same reason as docgen.go: the date stamp causes every regen to produce
		// a diff, which would break the cli-man-stale-check.yml CI guard.
		RootCmd.DisableAutoGenTag = true

		header := &doc.GenManHeader{
			Title:   "BCDOCK",
			Section: "1",
			Date:    &[]time.Time{time.Date(2025, 1, 1, 0, 0, 0, 0, time.UTC)}[0],
			Source:  "BCDock CLI",
			Manual:  "BCDock Manual",
		}

		return doc.GenManTree(RootCmd, header, out)
	},
}

func init() {
	mangenCmd.Flags().String("out", "", "Output directory for generated man pages (required)")
	RootCmd.AddCommand(mangenCmd)
}
