.nh
.TH "BCDOCK" "1" "Jan 2025" "BCDock CLI" "BCDock Manual"

.SH NAME
bcdock-completion-fish - Generate the autocompletion script for fish


.SH SYNOPSIS
\fBbcdock completion fish [flags]\fP


.SH DESCRIPTION
Generate the autocompletion script for the fish shell.

.PP
To load completions in your current shell session:

.EX
bcdock completion fish | source
.EE

.PP
To load completions for every new session, execute once:

.EX
bcdock completion fish > ~/.config/fish/completions/bcdock.fish
.EE

.PP
You will need to start a new shell for this setup to take effect.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for fish

.PP
\fB--no-descriptions\fP[=false]
	disable completion descriptions


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-url\fP=""
	API base URL (env: BCDOCK_API_URL)

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format: table, json, csv

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--timeout\fP=30s
	Request timeout

.PP
\fB--token\fP=""
	API token (env: BCDOCK_TOKEN)


.SH SEE ALSO
\fBbcdock-completion(1)\fP
