.nh
.TH "BCDOCK" "1" "Jan 2025" "BCDock CLI" "BCDock Manual"

.SH NAME
bcdock-config - Discover available regions and configurations


.SH SYNOPSIS
\fBbcdock config [flags]\fP


.SH DESCRIPTION
Discover what Azure regions and BC configurations the BCDock platform supports.

.PP
For BC version and country discovery, prefer 'bcdock artifacts list' which
also shows pre-built image availability (FAST column).

.PP
Exit codes:
  0   ok
  1   general error


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for config


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-url\fP=""
	API base URL (env: BCDOCK_API_URL)

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format: table, json, csv

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--timeout\fP=30s
	Request timeout

.PP
\fB--token\fP=""
	API token (env: BCDOCK_TOKEN)


.SH EXAMPLE
.EX
  bcdock config regions
  bcdock config regions -o json
.EE


.SH SEE ALSO
\fBbcdock(1)\fP, \fBbcdock-config-list(1)\fP, \fBbcdock-config-regions(1)\fP, \fBbcdock-config-versions(1)\fP
