.nh
.TH "BCDOCK" "1" "Jan 2025" "BCDock CLI" "BCDock Manual"

.SH NAME
bcdock-config-versions - List available BC versions (use 'bcdock artifacts list' instead)


.SH SYNOPSIS
\fBbcdock config versions [flags]\fP


.SH DESCRIPTION
List available BC versions. This command is not yet implemented - use
\&'bcdock artifacts list' to browse versions with pre-built image information.

.PP
Exit codes:
  1   general error (not yet implemented)


.SH OPTIONS
\fB--country\fP=""
	Filter by country

.PP
\fB--fast-only\fP[=false]
	Only versions with pre-built images

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for versions

.PP
\fB--region\fP=""
	Filter by region


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-url\fP=""
	API base URL (env: BCDOCK_API_URL)

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format: table, json, csv

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--timeout\fP=30s
	Request timeout

.PP
\fB--token\fP=""
	API token (env: BCDOCK_TOKEN)


.SH EXAMPLE
.EX
  bcdock artifacts list --region australiaeast --fast-only
.EE


.SH SEE ALSO
\fBbcdock-config(1)\fP
